version: "3.6"


services:
  postgres:
    container_name: risk_postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    image: postgres:14
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./packages/server/lib/infrastructure/database/migrations/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./packages/server/lib/infrastructure/database/migrations/prefill.sql:/docker-entrypoint-initdb.d/prefill.sql

  webserver:
    build: .
    container_name: risk_webserver_container
    depends_on:
      - postgres
    image: risk_webserver
    ports:
      - "8090:8090"

  ngrok:
    command: ["http", "webserver:8090"]
    container_name: ngrok_container
    depends_on:
      - webserver
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    image: ngrok/ngrok:debian
    ports:
      - "4040:4040"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml


volumes:
    postgres:
    ngrok: